import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { MapPin, Calendar, Sparkles, Plane, ChevronRight, Share2, Download, Edit3 } from "lucide-react";
import { Itinerary } from "./types";
import { MOCK_ITINERARY } from "./mockData";
import { DayView } from "./components/DayView";
import { cn } from "./lib/utils";

export default function App() {
  const [itinerary, setItinerary] = useState<Itinerary>(MOCK_ITINERARY);
  const [activeDay, setActiveDay] = useState(0);

  const handleShare = () => {
    const text = `Check out my itinerary for ${itinerary.destination}!\n\nGenerated by Voyageur AI`;
    navigator.clipboard.writeText(window.location.href);
    alert("Link copied to clipboard!");
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Hero Section */}
      <header className="relative h-[40vh] min-h-[400px] overflow-hidden bg-slate-900">
        <div className="absolute inset-0 opacity-50">
          <img 
            src={`https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2070&auto=format&fit=crop`}
            alt={itinerary.destination}
            className="h-full w-full object-cover"
            referrerPolicy="no-referrer"
          />
        </div>
        <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/20 to-transparent" />
        
        <div className="relative mx-auto flex h-full max-w-7xl flex-col items-center justify-end pb-12 px-4 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="mb-4 flex items-center justify-center gap-2 text-primary">
              <Plane className="h-5 w-5" />
              <span className="text-xs font-bold uppercase tracking-widest">Voyageur AI</span>
            </div>
            <h1 className="mb-4 text-4xl font-extrabold text-white md:text-6xl">
              {itinerary.destination}
            </h1>
            <div className="flex items-center justify-center gap-4 text-slate-300">
              <div className="flex items-center gap-1.5">
                <Calendar className="h-4 w-4" />
                <span className="text-sm font-medium">{itinerary.duration} Days</span>
              </div>
              <div className="h-1 w-1 rounded-full bg-slate-500" />
              <div className="flex items-center gap-1.5">
                <MapPin className="h-4 w-4" />
                <span className="text-sm font-medium">Personal Trip</span>
              </div>
            </div>
          </motion.div>
        </div>
      </header>

      {/* Main Content */}
      <main className="mx-auto max-w-7xl px-4 py-12">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-3">
          {/* Sidebar Info */}
          <div className="lg:col-span-1">
            <div className="sticky top-8 space-y-6">
              {/* Summary Card */}
              <div className="rounded-3xl bg-white p-8 shadow-sm border border-slate-100">
                <h3 className="text-lg font-bold text-slate-900 mb-4">Trip Summary</h3>
                <p className="text-slate-600 leading-relaxed text-sm italic">
                  "{itinerary.summary}"
                </p>
                
                <div className="mt-8 flex flex-wrap gap-3">
                  <button 
                    onClick={handleShare}
                    className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white transition-all hover:bg-slate-800"
                  >
                    <Share2 className="h-4 w-4" />
                    Share
                  </button>
                  <button className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-600 transition-all hover:bg-slate-50">
                    <Download className="h-4 w-4" />
                  </button>
                </div>
              </div>

              {/* Day Selector */}
              <div className="space-y-2">
                <h3 className="px-4 text-xs font-bold uppercase tracking-widest text-slate-400 mb-2">Itinerary Timeline</h3>
                {itinerary.days.map((day, idx) => (
                  <button
                    key={idx}
                    onClick={() => setActiveDay(idx)}
                    className={cn(
                      "group flex w-full items-center justify-between rounded-2xl p-4 transition-all",
                      activeDay === idx 
                        ? "bg-primary text-white shadow-lg shadow-primary/20" 
                        : "bg-white text-slate-600 hover:bg-slate-100 border border-transparent hover:border-slate-200"
                    )}
                  >
                    <div className="flex flex-col items-start">
                      <span className={cn(
                        "text-[10px] font-bold uppercase tracking-wider",
                        activeDay === idx ? "text-white/80" : "text-slate-400"
                      )}>Day {day.day}</span>
                      <span className="font-semibold text-sm line-clamp-1">{day.theme}</span>
                    </div>
                    <ChevronRight className={cn(
                      "h-4 w-4 transition-transform",
                      activeDay === idx ? "translate-x-0 opacity-100" : "-translate-x-2 opacity-0 group-hover:translate-x-0 group-hover:opacity-50"
                    )} />
                  </button>
                ))}
              </div>

              {/* Edit Placeholder */}
              <div className="rounded-2xl border-2 border-dashed border-slate-200 p-6 text-center">
                <Edit3 className="mx-auto h-6 w-6 text-slate-300 mb-2" />
                <p className="text-xs text-slate-400 font-medium">
                  Want to customize this? <br />
                  <span className="text-primary cursor-pointer hover:underline">Edit Itinerary</span>
                </p>
              </div>
            </div>
          </div>

          {/* Day Details */}
          <div className="lg:col-span-2">
            <AnimatePresence mode="wait">
              <motion.div
                key={activeDay}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3 }}
                className="rounded-3xl bg-white p-8 md:p-12 shadow-sm border border-slate-100"
              >
                <DayView dayPlan={itinerary.days[activeDay]} />
              </motion.div>
            </AnimatePresence>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-12 mt-20">
        <div className="mx-auto max-w-7xl px-4 text-center">
          <div className="flex items-center justify-center gap-2 text-slate-400">
            <Plane className="h-5 w-5" />
            <span className="text-sm font-bold uppercase tracking-widest">Voyageur AI</span>
          </div>
          <p className="mt-4 text-sm text-slate-500">
            © 2026 Voyageur AI. Your personal travel companion.
          </p>
        </div>
      </footer>
    </div>
  );
}
